version: "0.1"
name: pfe

services:
    jupyter:
        # image: ./Dockerfile.jupyter
        container_name: jupyter
        build:
            context: .
            dockerfile: Dockerfile.jupyter
        ports:
            - "8888:8888"
        volumes:
            - ./Emotion-detection:/home/jovyan/work
        environment:
            - JUPYTER_ENABLE_LAB=yes
            - GRANT_SUDO=yes
            - NB_UID=1000
            - NB_GID=100
            - JUPYTER_TOKEN=pfe
            # set work directory to /home/jovyan/work
            - WORK_DIR=/home/jovyan/work

# docker-compose up --build