name: Ignore Directory in Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ignore_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user identity
        run: |
          git config user.email "lucas.trubiano@gmail.com"
          git config user.name "lucastrubiano"
          
      - name: Fetch base branch
        run: |
          base_branch=${{ github.base_ref }}
          git fetch origin $base_branch:$base_branch
          
      - name: Checkout base branch
        run: git checkout ${{ github.base_ref }}

      - name: Preserve allowed files and directories
        run: |
          # List of allowed files and directories
          allowed=("images" "models" "src" ".env" ".gitignore" "main.py" "README.md" "requirements.txt")
          
          # Remove all files and directories except allowed ones
          removed=""
          for entry in *; do
            if [[ ! " ${allowed[@]} " =~ " $entry " ]]; then
              rm -rf "$entry"
              removed="$removed $entry"
            fi
          done
          
          if [[ ! -z "$removed" ]]; then
            echo "Removed files and directories:$removed"
            git add -A
            git commit -m "Remove unnecessary files and directories"
            git push origin HEAD:${{ github.base_ref }}
          else
            echo "No files or directories to remove"
          fi

      - name: Push changes to pull request branch
        run: git push origin HEAD:${{ github.base_ref }}
